baseURL = 'https://nickvourd.github.io/'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
title = 'nickvourd'
theme = 'hugo-coder'

paginate = 20
canonifyURLs = true

enableEmoji = true
enableGitInfo = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[markup.highlight]
style = "github-dark"
tabWidth = 4

[params]
author = "Nikos Vourdas"
description = "nickvourd InfoSec blog"
faviconSVG = "images/favicon.ico"
avatarURL = "images/fox-logo-200x200.png"
images = ["images/fox-ncv.png"]
keywords = "blog,personal,cyber,security,offensive,active,directory,azure,cloud,entra"
info = "Offensive Security Legacy"

dateFormat = "January 2, 2006"

colorScheme = "dark"
hideColorSchemeToggle = true

customSCSS = ["scss/custom.scss"]

[params.goatCounter]
code = "nickvourd"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/nickvourd/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 2
url = "https://twitter.com/nickvourd/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 3
url = "https://linkedin.com/in/nickvourd/"

[[params.social]]
name = "Email"
icon = "fa-solid fa-envelope fa-2x"
weight = 4
url = "mailto:nickvourd97@gmail.com"

[[params.social]]
name = "Certifications"
icon = "fa-solid fa-wallet fa-2x"
weight = 5
url = "https://www.credential.net/profile/nickvourd/wallet"

[[params.social]]
name = "Buy me a coffee"
icon = "fa-solid fa-beer fa-2x"
weight = 6
url = "https://buymeacoffee.com/nickvourd"

[[params.social]]
name = "RSS"
icon = "fa fa-rss fa-2x"
weight = 7
url = "/posts/index.xml"

[[menu.main]]
name = "Posts"
weight = 1
url = "posts/"

[[menu.main]]
name = "About"
weight = 2
url = "about/"
