baseURL = 'https://nickvourd.github.io/'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
title = 'nickvourd'
theme = 'hugo-coder'

paginate = 20
canonifyURLs = true

enableEmoji = true
enableGitInfo = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[markup.highlight]
style = "github-dark"
tabWidth = 4

[params]
author = "Nikos Vourdas"
description = "nickvourd InfoSec blog"
avatarURL = "images/fox-logo-200x200.png"
keywords = "blog,personal,active,directory,azure,cloud,cyber,security,penetration,test"
info = "Offensive Security Blog"

dateFormat = "2006-01-02"

colorScheme = "dark"
hideColorSchemeToggle = true
